version: 1
id: wto.ysm_branding
name: WTO with YSM Branding
description: Shows WTO branding when playing with YSM.
scope: prod
scripts:
  - path: brand-ysm.ts
    tests:
      - brand-ysm.test.ts
variables:
  branding:
    YSM: WARNO Tactical Overhaul
    YSMTIT: WARNO Tactical Overhaul
    YSMMT: WTO balance rules with YSM sandbox content
